export const ActionTypes = {
  CHANGE_SETTINGS: 'CHANGE_SETTINGS',
  FETCH_RESULTS:'FETCH_RESULTS',
  SET_RESULTS:'SET_RESULTS',
  ERROR_FETCHING_RESULTS:'ERROR_FETCHING_RESULTS',
  CLEAR_ERROR: 'CLEAR_ERROR'
};
